services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
      RAM_SIZE: "4G" # Change the RAM Size
      DISK_SIZE: "64G" # Change the disk size
      CPU_CORES: "2" #Change this to Change the number of CPU Cres the VM has access to
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
