services:
  windows:
    container_name: windows
    image: dockurr/windows
    securityContext:
      privileged: true
      capabilities:
        add: ["NET_ADMIN","NET_RAW"]
    environment:
      VERSION: "win11e"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
